# Generated by Django 3.1.1 on 2020-09-15 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geocoder.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=geocoder.models.upload_location)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoder.map')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocoder_taggedmap_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='map',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='geocoder.TaggedMap', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='map',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
